apiVersion: v1
kind: Service
metadata:
  name: go-web-app
  labels:
   app: go-web-app
spec:
  ports:
    -  port: 80 
       protocol: TCP
       targetPort: 8081
  selector:
    app : go-web-app
    type: ClusterIP 